version: "3.7"
services:
  api:
    extends:
      file: docker-compose.yaml
      service: api
    hostname: test_api
    build:
      context: ./api
      dockerfile: ./Dockerfile
      target: DEV
    environment:
      - API_PG_PWD=pass1
      - DOCKER_AMQP_HOST=test_rabbitmq:5672
      - DOCKER_AMQP_VHOST=dev
      - DOCKER_AMQP_USERNAME=guest
      - DOCKER_AMQP_PWD=guest

  bookings:
    extends:
      file: docker-compose.yaml
      service: bookings
    hostname: test_bookings
    build:
      context: ./bookings
      dockerfile: ./Dockerfile
      target: DEV
    environment:
      - BOOKINGS_PG_PWD=pass1
      - DOCKER_AMQP_HOST=test_rabbitmq:5672
      - DOCKER_AMQP_VHOST=dev
      - DOCKER_AMQP_USERNAME=guest
      - DOCKER_AMQP_PWD=guest

  postgres:
    extends:
      file: docker-compose.yaml
      service: postgres
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: root

  rabbit-dev:
    extends:
      file: docker-compose.yaml
      service: rabbit-dev
    hostname: test_rabbitmq
    container_name: test_rabbitmq

  test:
    container_name: e2e-test
    build:
      context: ./e2e_test
      dockerfile: ./Dockerfile
    environment:
      - BOOKINGS_PG_PWD=pass1
    depends_on:
      - bookings
      - api
#    volumes:
#      - ./bookings/dist/src:/workspace/dist/src
#      - ./bookings/src:/workspace/src
    ports:
      - 4200:4200
volumes:
  workspace: