version: "3.7"
services:
  api:
    extends:
      file: docker-compose.yaml
      service: api
    hostname: test_api
    build:
      context: ./api
      dockerfile: ./Dockerfile
      target: TEST
    environment:
      - API_PG_PWD=pass1
    depends_on:
      postgres:
        condition: service_healthy
      rabbit-dev:
        condition: service_healthy

  bookings:
    extends:
      file: docker-compose.yaml
      service: bookings
    hostname: test_bookings
    depends_on:
      postgres:
        condition: service_healthy
      rabbit-dev:
        condition: service_healthy
    build:
      context: ./bookings
      dockerfile: ./Dockerfile
      target: DEV
    environment:
      - BOOKINGS_PG_PWD=pass1
      - DOCKER_AMQP_HOST=test_rabbitmq:5762

  postgres:
    extends:
      file: docker-compose.yaml
      service: postgres
    hostname: test_postgres
    environment:
      PG_USER: user1
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pass1
      POSTGRES_DB: api-db
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120

  rabbit-dev:
    extends:
      file: docker-compose.yaml
      service: rabbit-dev
    hostname: test_rabbitmq

volumes:
  workspace: