version: "3.7"
services:
  api:
    extends:
      file: docker-compose.yaml
      service: api
    build:
      context: ./api
      dockerfile: ./Dockerfile
      target: DEV
    environment:
      - API_PG_PWD=pass1
      - DOCKER_AMQP_HOST=rabbit-dev:5672
      - DOCKER_AMQP_VHOST=dev
      - DOCKER_AMQP_USERNAME=guest
      - DOCKER_AMQP_PWD=guest

  bookings:
    extends:
      file: docker-compose.yaml
      service: bookings
    build:
      context: ./bookings
      dockerfile: ./Dockerfile
      target: DEV
    environment:
      - BOOKINGS_PG_PWD=pass1
      - DOCKER_AMQP_HOST=rabbit-dev:5672
      - DOCKER_AMQP_VHOST=dev
      - DOCKER_AMQP_USERNAME=guest
      - DOCKER_AMQP_PWD=guest


  postgres:
    extends:
      file: docker-compose.yaml
      service: postgres

  rabbit-dev:
    extends:
      file: docker-compose.yaml
      service: rabbit-dev

volumes:
  workspace: